module.exports = function (app) {
    app.get('/cadastroUsuario',function(req,res){
        app.app.controllers.admin.renderCadastroUsuario(app,req,res)
    })
    app.post('/admin/cadastrar',function(req,res){
        app.app.controllers.admin.CadastrarUsuario(app,req,res)
    })
    app.get('/admin/menu',function(req,res){
        app.app.controllers.admin.renderMenu(app,req,res)
    })
    app.get('/listaUsuarios',function(req,res){
        app.app.controllers.admin.renderUsuarios(app,req,res)
    })
    app.post('/admin/editarUsuario',function(req,res){
        app.app.controllers.admin.editarUsuario(app,req,res)
    })
    app.post('/admin/salvarUsuario',function(req,res){
        app.app.controllers.admin.salvarUsuario(app,req,res)
    })
    app.post('/admin/editarSenhaUsuario',function(req,res){
        app.app.controllers.admin.editarSenhaUsuario(app,req,res)
    })
    app.post('/admin/salvarSenhaUsuario',function(req,res){
        app.app.controllers.admin.salvarSenhaUsuario(app,req,res)
    })
    app.post('/admin/excluirUsuario',function(req,res){
        app.app.controllers.admin.excluirUsuario(app,req,res)
    })
    app.get('/cadastroProduto',function(req,res){
        app.app.controllers.admin.renderCadastroProduto(app,req,res)
    })
    app.post('/admin/cadastrarProduto',function(req,res){
        app.app.controllers.admin.cadastrarProduto(app,req,res)
    })
    app.get('/listaProdutos',function(req,res){
        app.app.controllers.admin.renderListaProdutos(app,req,res)
    })
    app.get('/admin/listaProdutos',function(req,res){
        app.app.controllers.admin.renderListaProdutos(app,req,res)
    })
    app.post('/admin/editarProduto',function(req,res){
        app.app.controllers.admin.editarProduto(app,req,res)
    })
    app.post('/admin/salvarProduto',function(req,res){
        app.app.controllers.admin.salvarProduto(app,req,res)
    })
    app.post('/admin/excluirProduto',function(req,res){
        app.app.controllers.admin.excluirProduto(app,req,res)
    })
    app.get('/listaPedidosAbertos',function(req,res){
        app.app.controllers.admin.listaPedidosAbertos(app,req,res)
    })
    app.post('/admin/concluirCompra',function(req,res){
        app.app.controllers.admin.concluirCompra(app,req,res)
    })
}